config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :tasks, only: [:new, :create, :index, :show, :destroy]
	
	root 'tasks#index' 

	put 'task/:id/done', to: 'tasks#done', as: 'task_done'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

	validates :name, presence: { message: "El nombre es obligatorio!"} 
	belongs_to :user
	scope :all_desc_order_of, -> (user) { where(user: user).order(created_at: :desc) }
	scope :dones_of, -> (user) { where(is_done: true, user: user) }
	scope :undones_of, -> (user) { where(is_done: false, user: user) } 

	before_create :set_created

	def done
		unless self.is_done
			self.is_done = true
			return self.save
		end

		self.errors[:is_done] << "Esta tarea ya fue terminada!"
		return false
	end

	private
	def set_created
		self.created = DateTime.now
	end	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :set_task, only:[:show, :done, :destroy]
	before_action :authenticate_user!

	def index
		@tasks = Task.all_desc_order_of current_user
	end

	def new
		@task = Task.new
		respond_to do |format|
			format.html
			format.js
		end	
	end

	def show
	
	end	

	def create
		@task = Task.new task_params
		@task.user = current_user 
		
		if @task.save
			msj = "La tarea #{@task.name} ha sido añadida a tu lista de tareas!"
			redirect_to tasks_path, notice: msj
		else
			render :new
		end

	end

	def done

		if @task.done
			msj = "Haz terminado la tarea #{@task.name}!"
			redirect_to tasks_path, notice: msj
		else
			render :show
		end

	end

	def destroy
		
		if @task.destroy
			msj = "La tarea #{@task.name} ha sido eliminada."
			redirect_to tasks_path, notice: msj	
		end	
	
	end	

	private
	def task_params
		params.require(:task).permit(:name, :user)
	end

	def set_task
		@task = Task.find(params[:id])
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

	def show_status(task)
		data = {text: "pendiente", clase: "badge-warning"}
		
		if task.is_done
			data = {text: "terminada", clase: "badge-success"}
			return data
		end	

		data
	end

	def show_date(task, fecha_actual=DateTime.now)
		if es_de_hoy(task, fecha_actual)
			return 'Hoy'
		else
			return task.created.strftime('%a, %d %B %Y')
		end	
	end

	private
	def es_de_hoy(task, fecha_actual)
		Date.parse(task.created.to_s).eql?(Date.parse(fecha_actual.to_s))
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <div id="modals"></div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row offset-md-2 mt-4">
	<div class="col-12 col-md-10">
		<div id="tarea-modal" tabindex="-1" role="dialog" class="modal fade">
			<div class="modal-dialog" role="document">
				<div class="modal-content">	
					<div class="modal-header">
						<h4 class="modal-title"> <%= accion %> </h4>
						<button type="button" class="close" data-dismiss="modal" arial-label="Cerrar">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<%= form_for @task, remote: true do |f| %>
						<div class="modal-body">
							<%= render "tasks/msjs_de_error", task: @task %>
							<div class="form-group">
								<%= f.label :name %>
								<%= f.text_field :name, class: 'form-control' %>
							</div>
						</div>
						<div class="modal-footer">
							<%= f.submit t('.save'), class: 'btn btn-outline-success', id: 'btn-guardar' %>
							<%= link_to t('.cancel'), tasks_path, class: 'btn btn-secondary', id: 'btn-cancelar' %>
						</div>
					<% end %>
				</div>
			</div>
	  </div>
	</div>
</div>

app/views/tasks/_msjs_de_error.html.erb
<div class="row">
	<div class="col">
		<% if task.errors.any? %>
			<ul class="list-group list-unstyled mt-2">
			<% task.errors.full_messages.each do |msj| %>
				<li class="badge badge-pill badge-danger"> <%= msj %> </li>
			<% end %>
			</ul>
		<% end %>
	</div>	
</div>

app/views/tasks/_task.html.erb
<div class="row offset-md-2">
	<div class="col-12 col-md-10 mt-4">
		<article class="card">
			<div class="row mt-4">
				<div class="col-12">
					<h3 class="card-title ml-3"> <%= task.name %> </h3>
					<div class="row ml-2">
						<div class="col">
							<p> <span class="badge badge-pill <%= show_status(task)[:clase] %>"> <%= show_status(task)[:text] %> <i class="fa fa-tag"></i> </span></p>
						</div>
					</div>
				</div>
			</div>
			<div class="card-body">
				<%= link_to t('.done'), task_done_path(task), method: :put, id:"task_#{task.id}", class: "btn btn-outline-success" %>
				
				<%= link_to 'Eliminar', task, remote: true, method: :delete, class: 'btn btn-danger' %>
			</div>
			<div class="card-footer">
				<p> <i class="fa fa-calendar"></i> Creada <%= show_date(task) %> </p>
			</div>
		</article>
	</div>
</div>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
		<%= render tasks %>
<% else %>
	<div class="row">
		<div class="col-12 col-sm-10 col-md-8 offset-sm-1 offset-md-2 mt-4">
			<div class="alert alert-primary">
				<h2> <%= msj %></h2>
			</div>
		</div>
	</div>
<% end %>	

app/views/tasks/create.js.erb
<% if @task.errors.any? %>

	alert('<%= @task.errors.full_messages[0] %>');

<% else %>
	$('#tareas').append('<%= render "task", @task %>');
	$('#tarea-modal').modal('hide');
<% end %>

app/views/tasks/index.html.erb
<div class="row">
	<div class="col-10">
		<h2 class="display-4 mt-4"> <%= t('.title') %> </h2>
		<p><%= notice %> <%= alert %> </p>
		<hr>
	</div>	
	<div class="col-2 mt-2 mt-sm-4">
	<% if signed_in? %>
		<%= link_to "Salir", destroy_user_session_path, method: :delete, class: "btn btn-outline-info" %>
	<% end %>	
	</div>
</div>

<div class="tareas">
		<ul class="nav nav-tabs" id="myTab" role="tablist">
		  <div class="row offset-md-2 mr-2">
				<div class="col-12">
						<%= link_to '', new_task_path, class: 'btn btn-primary fa fa-plus', id: 'link-new', remote: true %>
				</div>
			</div>

		  <li class="nav-item">
		    <a class="nav-link" id="todas-tab" data-toggle="tab" href="#todas" role="tab" aria-controls="todas" aria-selected="true">Todas <strong> (<%= @tasks.count %>)</strong></a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="pendientes-tab" data-toggle="tab" href="#pendientes" role="tab" aria-controls="pendientes" aria-selected="false">Pendientes <strong> (<%= @tasks.undones_of(current_user).count %>)</strong></a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="terminadas-tab" data-toggle="tab" href="#terminadas" role="tab" aria-controls="terminadas" aria-selected="false">Terminadas <strong> (<%= @tasks.dones_of(current_user).count %>)</strong></a>
		  </li>
		</ul>
		<div class="tab-content" id="myTabContent">
		  <div class="tab-pane fade show active" id="todas" role="tabpanel" aria-labelledby="todas-tab">
		  	<%= render 'tasks', tasks: @tasks, msj: 'No tienes tareas creadas!'  %>	
		  </div>
		  <div class="tab-pane fade" id="pendientes" role="tabpanel" aria-labelledby="pendientes-tab">
		  	<%= render 'tasks', tasks: @tasks.undones_of(current_user), msj: 'No tienes tareas pendientes!'  %>
		  </div>
		  <div class="tab-pane fade" id="terminadas" role="tabpanel" aria-labelledby="terminadas-tab">
		  	<%= render 'tasks', tasks: @tasks.dones_of(current_user), msj: 'No tienes tareas terminadas!'  %>
		  </div>
		</div>
</div>

app/views/tasks/new.html.erb
<%= render "form", accion: t('.title') %>

app/views/tasks/new.js.erb
$('#modals').html('<%= j render "form", accion: t(".title") %>');
$('#tarea-modal').modal('show');
$('#modals').slideDown(300);

app/views/tasks/show.html.erb
<%= render "tasks/msjs_de_error", task: @task %>